[options]
realtime_leader_guide = 1
enable_vimfiler_welcome = 0
enable_debug = 1
enable_tabline_filetype_icon = 1
enable_statusline_display_mode = 0
enable_os_fileformat_icon = 0
buffer_index_type = 1
neomake_vim_enabled_makers = []
clang2_placeholder_next = ''
clang2_placeholder_prev = ''
colorscheme = "gruvbox"
colorscheme_bg = "dark"
guifont = "Hack Nerd Font:h16"

[[layers]]
name = "colorscheme"
[[layers]]
name = "incsearch"
[[layers]]
name = "lang#c"
[[layers]]
name = "lang#rust"
[[layers]]
name = "lang#vim"
[[layers]]
name = "shell"
[[layers]]
name = "sudo"
[[layers]]
name = "lsp"
[[layers]]
name = "fuzz"
[[layers]]
name = "direnv"
[[layers]]
name = "unite"
[[layers]]
name = "fzf"
